### ISSUE TITLE
Cuestionario

### ISSUE THREAD

**Issue by wilberquito** [2WolfGames/Erlang-Legacy#300]
El código se encuentra en la siguiente GitHub: https://github.com/2WolfGames/Erlang-Legacy y
podéis jugar el juego en la siguiente URL: https://2wolfgames.github.io/Erlang-Legacy/

Para poder jugar tener esto en cuenta. También pensad que las habilidades (dash y rayo) se desbloquean al pasar ciertas escenas.

Keys:
Shift: open menu
W: go up
S: go down / interact
A: move backward
D: move forward
J: punch
K: dash
L: ray
Space: jump / select

Os (Judit y Wilber) agradeceríamos mucho si podéis echarle un ojo y jugar y poder valorar el juego con el siguiente cuestionario.
Puede que os encontréis errores o cosas que no os permitan avanzar, esperamos que no, pero si es así, lo podéis poner en observaciones dentro del cuestionario sin remordimientos.

Parámetros a valorar:

Historia: trama, desarrollo de la narrativa, desarrollo, construcción y presentación de personajes, coherencia ludo narrativa.
[1-5]:

Jugabilidad: variedad y calidad de las mecánicas implementadas, sensaciones a la hora de jugar.
[1-5]:

Interacciones: variedad y calidad de las interacciones implementadas, enemigos, así como objetos de vida en el mapa, trampolines, agua, etc.
[1-5]:

Apartado artístico: diseño del mapeado, arte del juego, coherencia del mismo con el mundo propuesto.
[1-5]:

Apartado sonoro: efectos especiales, banda sonora, doblaje.
[1-5]:

Observaciones:
// bla bla bla

**Comment by wilberquito** [comment]
@Jumalita  que te parece este cuestionario, si tienes algo a añadir modifícalo o lo hablamos.

**Comment by Jumalita** [comment]
@wilberquito It's perfect.
You want to send it like this or we make a google form? Maybe will be better for our beta testers to fill a google form. 
And it so easy and fast to do.

**Comment by Jumalita** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeRkARynwkCMpRilAvr5tFYx0y2WAgUCC7t1fLvMGfzW0-o1A/viewform?usp=sf_link
